image:
  repository: memcached
  tag: alpine

statefulset:
  affinity: {}
  replicaCount: 1
  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 800Mi
      cpu: 500m

metrics:
  enabled: false
  image:
    repository: prom/memcached-exporter
    tag: v0.10.0
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 100Mi
      cpu: 100m
      
config:
  memoryLimitMB: 512
  verboseLogging: true
  maxConnections: 1024
  slabGrowthFactor: 1.25\
  slabPageSize: 1m
  minItemSize: 48
service:
  port: 11211
  type: ClusterIP