apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-config
  namespace: openstack
data:
  neutron.conf: |
    [DEFAULT]
    core_plugin = ml2
    service_plugins = router
    transport_url = rabbit://openstack:changeme123@rabbitmq.openstack-infra.svc.cluster.local:5672/
    auth_strategy = keystone
    notify_nova_on_port_status_changes = true
    notify_nova_on_port_data_changes = true
    
    [database]
    connection = mysql+pymysql://neutron:changeme123@mariadb.openstack-infra.svc.cluster.local/neutron
    
    [keystone_authtoken]
    www_authenticate_uri = http://keystone.openstack.svc.cluster.local:5000
    auth_url = http://keystone.openstack.svc.cluster.local:5000
    memcached_servers = memcached.openstack-infra.svc.cluster.local:11211
    auth_type = password
    project_domain_name = Default
    user_domain_name = Default
    project_name = service
    username = neutron
    password = changeme123
---
apiVersion: v1
kind: Service
metadata:
  name: neutron-server
  namespace: openstack
spec:
  ports:
    - port: 9696
      targetPort: 9696
      name: api
  selector:
    app: neutron-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neutron-server
  namespace: openstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neutron-server
  template:
    metadata:
      labels:
        app: neutron-server
    spec:
      containers:
      - name: neutron-server
        image: kolla/neutron-server:2024.1-ubuntu-jammy
        ports:
        - containerPort: 9696
          name: api
        volumeMounts:
        - name: neutron-config
          mountPath: /etc/neutron
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: neutron-config
        configMap:
          name: neutron-config
