apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
    {{ .Values.key | default "password" }}: {{ randAlphaNum 16 | b64enc | quote }}