apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-config
  namespace: openstack
data:
  cinder.conf: |
    [DEFAULT]
    transport_url = rabbit://openstack:changeme123@rabbitmq.openstack-infra.svc.cluster.local:5672/
    auth_strategy = keystone
    enabled_backends = lvm
    glance_api_servers = http://glance.openstack.svc.cluster.local:9292
    
    [database]
    connection = mysql+pymysql://cinder:changeme123@mariadb.openstack-infra.svc.cluster.local/cinder
    
    [keystone_authtoken]
    www_authenticate_uri = http://keystone.openstack.svc.cluster.local:5000
    auth_url = http://keystone.openstack.svc.cluster.local:5000
    memcached_servers = memcached.openstack-infra.svc.cluster.local:11211
    auth_type = password
    project_domain_name = Default
    user_domain_name = Default
    project_name = service
    username = cinder
    password = changeme123
    
    [lvm]
    volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
    volume_group = cinder-volumes
    target_protocol = iscsi
    target_helper = tgtadm
---
apiVersion: v1
kind: Service
metadata:
  name: cinder-api
  namespace: openstack
spec:
  ports:
    - port: 8776
      targetPort: 8776
      name: api
  selector:
    app: cinder-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinder-api
  namespace: openstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cinder-api
  template:
    metadata:
      labels:
        app: cinder-api
    spec:
      containers:
      - name: cinder-api
        image: kolla/cinder-api:2024.1-ubuntu-jammy
        ports:
        - containerPort: 8776
          name: api
        volumeMounts:
        - name: cinder-config
          mountPath: /etc/cinder
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: cinder-config
        configMap:
          name: cinder-config
